# Generated by Django 6.0.1 on 2026-01-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('memory', models.CharField(blank=True, max_length=20, null=True)),
                ('producer', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('product_code', models.IntegerField()),
                ('review_count', models.IntegerField(blank=True, default=0, null=True)),
                ('screen_diagonal', models.CharField(blank=True, max_length=10, null=True)),
                ('display_resolution', models.CharField(blank=True, max_length=50, null=True)),
                ('images', models.TextField()),
                ('characteristics', models.JSONField(default=dict)),
            ],
        ),
    ]
